apiVersion: istio-gateway-api-operator.io/v1alpha1
kind: Route
metadata:
  name: nginx
  namespace: default
spec:
  rules:
    - host: nginx.examples.com
      backend:
        serviceName: nginx
        servicePort: 80
