replicaCount: 1

image:
  repository: peishu/istio-gateway-api-operator
  tag: ""  # Defaults to appVersion
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

leaderElection:
  enabled: true

metrics:
  enabled: true
  port: 8443

webhook:
  enabled: true
  port: 9443

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

certManager:
  enabled: false
  issuerRef: {}
  # name: my-issuer
  # kind: ClusterIssuer
